name: drain
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
jobs:
  Drain:
    runs-on: ubuntu-latest
    environment: Development_2
    steps:
      - run: echo "🎉 Drain job was called"


