name: merged-pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Drain:
    runs-on: ubuntu-latest
    environment: Development_2
    steps:
      - run: echo "🎉 Drain job was called"

  Deploy:
      needs: Drain
      runs-on: ubuntu-latest
      environment: Development_2
      steps:
        - run: echo "🎉 Deploy job was called"
        - run: echo "🎉 Restore job was called"



