name: Release
run-name: Release ${{ inputs.ring }}/${{ inputs.region}}
on:
  workflow_dispatch:
    inputs:
      ring:
        type: choice
        description: "Ring"
        options:
          - lab
          - uat
          - prod
        required: true
        default: lab
      region:
        type: choice
        description: "Region where the deploy happen first"
        options:
          - eu_central
          - eu_west
          - east
          - west
        required: true
      flyway_migration:
        type: boolean
        description: "Flyway migration"
        default: false
      provision_ring:
        type: boolean
        description: "Provision Ring"
        default: false
      role:
        description: "Role (only required if Provision Ring is true): customer-smpp, nats, kms, mm4-static-enis, chatbot, rcs-load-balancer, rcs-intern-load-balancer"
        type: string

jobs:
  drain-restore:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ring }}
    steps:
      - run: echo "Release started"
      - name: Check if provisioning is enabled
        if: ${{ inputs.provision_ring == 'true'}}
        run: echo "Provision ring is set to true"

      - name: Convert roles into array
        if: ${{ inputs.provision_ring == 'true' && inputs.role != '' }}
        run: |
          ROLES="${{ inputs.role }}"
          IFS=',' read -r -a ROLE_ARRAY <<< "$ROLES"
          for role in "${ROLE_ARRAY[@]}"; do
            echo "Deploying role: $role"
          done