name: restore
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
jobs:
  Restore:
    runs-on: ubuntu-latest
    environment: Development_2
    steps:
      - run: echo "🎉 Restore job was called"


