name: restore
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Drain:
    runs-on: ubuntu-latest
    environment: Development_1
    steps:
      - run: echo "🎉 Drain job was called"

  Deploy:
    needs: Drain
    runs-on: ubuntu-latest
    environment: Development_2
    steps:
      - run: echo "🎉 Deploy job was called"


  Restore:
    needs: Deploy
    runs-on: ubuntu-latest
    environment: Development_2
    steps:
      - run: echo "🎉 Restore job was called"


