# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      param1:
        description: "Primul parametru"
        required: true
        type: string
      param2:
        description: "Al doilea parametru"
        required: true
        type: string
      param3:
        description: "Al treilea parametru"
        required: false
        type: boolean
      param4:
        description: "Al patrulea parametru"
        required: false
        type: string
  workflow_call:
    inputs:
      param1:
        description: "Primul parametru"
        required: true
        type: string
      param2:
        description: "Al doilea parametru"
        required: true
        type: string
      param3:
        description: "Al treilea parametru"
        required: false
        type: boolean
      param4:
        description: "Al patrulea parametru"
        required: false
        type: string

jobs:
  process:
    environment:
      name: ${{ github.event_name == 'workflow_call' && 'Development_1' || 'Development_2' }}
    runs-on: ubuntu-latest
    steps:
      - name: Afișează inputurile primite
        run: |
          echo "Param1: ${{ inputs.param1 }}"
          echo "Param2: ${{ inputs.param2 }}"
          echo "Param3: ${{ inputs.param3 }}"
          echo "Param4: ${{ inputs.param4 }}"
          echo ${{ github.event_name }}
  process2:
    runs-on: ubuntu-latest
    steps:
      - name: Afișează inputurile primite
        run: |
          echo "Param1: ${{ inputs.param1 }}"
          echo "Param2: ${{ inputs.param2 }}"
          echo "Param3: ${{ inputs.param3 }}"
          echo "Param4: ${{ inputs.param4 }}"
